apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: frigate
data:
  config.yml: |
    mqtt:
      enabled: false

    detectors:
      ov:
        type: openvino
        device: GPU

    ffmpeg:
      hwaccel_args: preset-vaapi

    record:
      enabled: true
      retain:
        days: 1
        mode: motion

    snapshots:
      enabled: true

    cameras: {}