apiVersion: v1
kind: Service
metadata:
  name: paintings-catalog-frontend
  namespace: paintings-catalog
spec:
  type: ClusterIP
  selector:
    app: paintings-catalog-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
