apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paintings-catalog-uploads
  namespace: paintings-catalog
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
